=== alexdeploy/daw-apuntes/1º Lenguajes de Marcas/Unidad 7 - DTD y XSD/Ejercicios DTD/Ejercicios DTD Parte I Resueltos/Soluciones Ejercicios DTD Parte I/libros.dtd
<!--Para el diseño de este DTD he supuesto que:
    - El elemento "web" puede o no aparecer.
    - El atributo "precio" he creido conveniente que sea obligatorio.
-->
<!ELEMENT catalogo (libreria*)>
<!ELEMENT libreria (libro+)>
<!ATTLIST libreria nombre CDATA #REQUIRED>
<!ATTLIST libreria web CDATA #IMPLIED>
<!ELEMENT libro (ISBN, tematica, titulo, autor+, editorial, fecha, web_site?, precio)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT tematica (#PCDATA)>
<!ATTLIST tematica nivel (Básico | Intermedio | Avanzado) #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ATTLIST fecha num_edicion NMTOKEN #REQUIRED>
<!ELEMENT web_site (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda (euro | dolar) #REQUIRED>

=== alexdeploy/daw-apuntes/1º Lenguajes de Marcas/Unidad 7 - DTD y XSD/Ejercicios DTD/Ejercicios DTD Parte I Resueltos/Soluciones Ejercicios DTD Parte I/libros.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "libros.dtd">
<catalogo>
	<libreria nombre="Ebooks Baratos" web="http://www.cheapebooks.com">
		<libro>
			<ISBN>123456789</ISBN>
			<tematica nivel="Básico">XML</tematica>
			<titulo>Introducción a XML</titulo>
			<autor>Perico de los palotes</autor>
			<autor>Antonio de los palotes</autor>
			<editorial>La cabaña de los cuentos</editorial>
			<fecha num_edicion="3">27 - 09 - 1999</fecha>
			<web_site>http://xmlintroduction.html</web_site>
			<precio moneda="euro">35.56</precio>
		</libro>
		<libro>
			<ISBN>987654321</ISBN>
			<tematica nivel="Avanzado">XML</tematica>
			<titulo>XML para expertos</titulo>
			<autor>Perico de los pimientos</autor>
			<autor>Antonio de las naranjas</autor>
			<editorial>La casa oscura</editorial>
			<fecha num_edicion="1">02 - 09 - 2002</fecha>
			<web_site><![CDATA[http://books.google.com.ec/books/about/XMLadvanced.html?hl=en&id=aI1vAAAACAAJ]]></web_site>
			<precio moneda="dolar">39.56</precio>
		</libro>
	</libreria>	
	<libreria nombre="Ebooks a tutti pleni" web="http://www.tuttipleniebooks.com">
		<libro>
			<ISBN>888987896</ISBN>
			<tematica nivel="Intermedio">XML</tematica>
			<titulo>XML pa el que se la pele</titulo>
			<autor>Camilo José Cela</autor>
			<autor>Juan Ramón Jimenez</autor>
			<editorial>Libros pirata</editorial>
			<fecha num_edicion="22">01 - 08 - 2011</fecha>
			<web_site>http://xmlpalqueselapele.html</web_site>
			<precio moneda="dolar">33000.55</precio>
		</libro>
		<libro>
			<ISBN>123456789</ISBN>
			<tematica nivel="Básico">XML</tematica>
			<titulo>Introducción a XML</titulo>
			<autor>Perico de los palotes</autor>
			<autor>Antonio de los palotes</autor>
			<editorial>La cabaña de los cuentos</editorial>
			<fecha num_edicion="3">27 - 09 - 1999</fecha>
			<web_site>http://xmlintroduction.html</web_site>
			<precio moneda="euro">10.56</precio>
		</libro>
	</libreria>
</catalogo>
