=== alexdeploy/daw-apuntes/1º Lenguajes de Marcas/Evaluable Final/ejercicio1.dtd
<!ELEMENT music (discs)>
<!ELEMENT discs (disc+)>
<!ELEMENT disc (#PCDATA | premiere | title | group | singer)*>
<!ELEMENT premiere (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT group (#PCDATA)>
<!ELEMENT singer (#PCDATA)>
<!ATTLIST disc titulo CDATA #REQUIRED>
<!ATTLIST group fecha_nacimiento CDATA #IMPLIED>
<!ATTLIST group pais_nacimiento CDATA #IMPLIED>
<!ATTLIST singer fecha_nacimiento CDATA #IMPLIED>
<!ATTLIST singer pais_nacimiento CDATA #IMPLIED>

<!-- Nombre: Alejandro Soriano Rueda-->

=== alexdeploy/daw-apuntes/1º Lenguajes de Marcas/Evaluable Final/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE music SYSTEM "ejercicio1.dtd">
<music xmlns:xsi ="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation ="ejercicio1.xsd">
   <discs>
     <disc titulo="El rey de los corderos">
     The King of Limbs is the eighth studio album by English rock band Radiohead, produced by Nigel Godrich. ...
       <premiere>2011</premiere>
       <title>The King of Limbs</title>
       <group fecha_nacimiento="1985" pais_nacimiento="UK" >Radiohead</group>
     </disc>
     <disc titulo="Ok, ordenador">
     OK Computer is the third studio album by the English alternative rock band Radiohead,.....
       <premiere>1991</premiere>
       <title>OK Computer</title>
       <group fecha_nacimiento="2011" pais_nacimiento="UK">Radiohead</group>
       <singer fecha_nacimiento="1968" pais_nacimiento="UK" >Thom Yorke</singer>
     </disc>
     <disc titulo="Atontao">
     Dummy is the debut album of the Bristol-based group Portishead. Released in August 22, 1994 on Go! Discs, the album earned critical....
       <premiere>1994</premiere>
       <title>Dummy</title>
       <group fecha_nacimiento="1991" pais_nacimiento="UK" >Portishead</group>
       <singer fecha_nacimiento="1965" >Beth Gibbons </singer>
     </disc>
     <disc titulo="Tercero">
     Third is the third studio album by English musical group Portishead, released on 27 April 2008, on Island Records.....
       <premiere>2008</premiere>
       <title>Third</title>
       <group fecha_nacimiento="1991" pais_nacimiento="UK" >Portishead</group>
       <singer fecha_nacimiento="1965">Beth Gibbons </singer>
     </disc>
     <disc titulo="El arbol de Josue">
     Aclamado con magníficas críticas, muchos lo calificaron de obra maestra. Este disco se convirtió en su primer ....
       <premiere>1986</premiere>
       <title>The Joshua Tree</title>
       <group pais_nacimiento="Ireland">U2</group>
       <singer fecha_nacimiento="1960">Bono</singer>
     </disc>
   </discs>
</music>
