=== alexdeploy/daw-apuntes/1º Lenguajes de Marcas/Evaluable Final/ejercicio2.dtd
<!ELEMENT coches (fecha_actualizado, (coche | multa)+)>
<!ELEMENT fecha_actualizado (#PCDATA)>
<!ELEMENT coche (#PCDATA)>
<!ELEMENT multa (#PCDATA)>
<!ATTLIST coche matricula ID #REQUIRED>
<!ATTLIST multa matricula IDREF #REQUIRED>


<!-- Nombre: Alejandro Soriano Rueda-->

=== alexdeploy/daw-apuntes/1º Lenguajes de Marcas/Evaluable Final/ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE coches SYSTEM "ejercicio2.dtd">
<coches>
   <fecha_actualizado>11/05/2020</fecha_actualizado>
   <coche matricula="L1">1234abc</coche>
   <multa matricula="L1">100</multa>
   <coche matricula="L2">2345tre</coche>
   <multa matricula="L2">200</multa>
   <coche matricula="L3">3434feo</coche>
   <coche matricula="L4">2233ytu</coche>
   <coche matricula="L5">2233mas</coche>
   <multa matricula="L3">100</multa>
   <multa matricula="L4">133</multa>
</coches>
