<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE oferta [
<!ELEMENT oferta (vehiculo+)>
<!ELEMENT vehiculo (marca, modelo, motor, matricula, kilometros, precio_inicial, precio_oferta, extra+, foto+)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT motor (#PCDATA)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT kilometros (#PCDATA)>
<!ELEMENT precio_inicial (#PCDATA)>
<!ELEMENT precio_oferta (#PCDATA)>
<!ELEMENT extra (#PCDATA)>
<!ELEMENT foto (#PCDATA)>
<!ATTLIST modelo color CDATA #REQUIRED>
<!ATTLIST motor combustible ( gasolina | diesel ) #REQUIRED>
<!ATTLIST extra valor CDATA #REQUIRED>
]>
<oferta>
	<vehiculo>
		<marca>ford</marca>
		<modelo color="gris">focus</modelo>
		<motor combustible="gasolina">duratore 1.4</motor>
		<matricula>1234AAAA</matricula>
		<kilometros>12500</kilometros>
		<precio_inicial>12000</precio_inicial>
		<precio_oferta>10000</precio_oferta>
		<extra valor="250">llantas</extra>
		<extra valor="300">pintura metalizada</extra>
		<foto>11325.jpg</foto>
		<foto>11326.jpg</foto>	
	</vehiculo>
	<vehiculo>
		<marca>ford</marca>
		<modelo color="gris">focus</modelo>
		<motor combustible="diesel">duratore 2.0</motor>
		<matricula>12345AAA</matricula>
		<kilometros>125000</kilometros>
		<precio_inicial>10000</precio_inicial>
		<precio_oferta>9000</precio_oferta>
		<extra valor="250">pintura metalizada</extra>
		<extra valor="200">spoiler trasero</extra>
		<extra valor="500">climatizador</extra>
		<foto>11327.jpg</foto>
		<foto>11328.jpg</foto>	
	</vehiculo>
</oferta>